// Code generated by "stringer -type=NmDeviceInterfaceFlags"; DO NOT EDIT.

package gonetworkmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NmDeviceInterfaceFlagsNone-0]
	_ = x[NmDeviceInterfaceFlagsUp-1]
	_ = x[NmDeviceInterfaceFlagsLowerUp-2]
	_ = x[NmDeviceInterfaceFlagsPromisc-4]
	_ = x[NmDeviceInterfaceFlagsCarrier-65536]
	_ = x[NmDeviceInterfaceFlagsLldpClientEnabled-131072]
}

const (
	_NmDeviceInterfaceFlags_name_0 = "NmDeviceInterfaceFlagsNoneNmDeviceInterfaceFlagsUpNmDeviceInterfaceFlagsLowerUp"
	_NmDeviceInterfaceFlags_name_1 = "NmDeviceInterfaceFlagsPromisc"
	_NmDeviceInterfaceFlags_name_2 = "NmDeviceInterfaceFlagsCarrier"
	_NmDeviceInterfaceFlags_name_3 = "NmDeviceInterfaceFlagsLldpClientEnabled"
)

var (
	_NmDeviceInterfaceFlags_index_0 = [...]uint8{0, 26, 50, 79}
)

func (i NmDeviceInterfaceFlags) String() string {
	switch {
	case i <= 2:
		return _NmDeviceInterfaceFlags_name_0[_NmDeviceInterfaceFlags_index_0[i]:_NmDeviceInterfaceFlags_index_0[i+1]]
	case i == 4:
		return _NmDeviceInterfaceFlags_name_1
	case i == 65536:
		return _NmDeviceInterfaceFlags_name_2
	case i == 131072:
		return _NmDeviceInterfaceFlags_name_3
	default:
		return "NmDeviceInterfaceFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
